using FixedMathSharp;

namespace Gravitas;

/// <summary>
/// Deterministic pure 2D contact data generated by the 2D narrow phase.
/// </summary>
public readonly struct Contact2D
{
    public Contact2D(Vector2d pointA, Vector2d pointB, Vector2d normal, Fixed64 depth)
    {
        PointA = pointA;
        PointB = pointB;
        Normal = normal;
        Depth = depth;
        HasContact = true;
    }

    public bool HasContact { get; }

    public Vector2d PointA { get; }

    public Vector2d PointB { get; }

    /// <summary>
    /// Contact normal pointing from collider A toward collider B.
    /// </summary>
    public Vector2d Normal { get; }

    public Fixed64 Depth { get; }
}
